[package]
name = "agentduels_protocol"
version.workspace = true
edition.workspace = true

[dependencies]
agentduels_protocol_macros = { version = "0.1.0", path = "macros" }
postcard.workspace = true
serde.workspace = true
