[package]
name = "agentduels_server"
version.workspace = true
edition.workspace = true

[dependencies]
actix-web = "4.11.0"
agentduels_protocol.workspace = true
anyhow.workspace = true
dashmap = "6.1.0"
rand.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["full"] }
